default: &default
  adapter: postgresql
  user: rizvan
  password: new life
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: sample_app_development

test:
  <<: *default
  database: sample_app_test
production:
  <<: *default
  database: sample_app_production